frequency: 30.0
sensor_timeout: 0.034
two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map

# Odometry input
odom0: odom
odom0_config: [false, false, false,     # Position (x, y, z)
              false, false, false,      # Orientation (roll, pitch, yaw)
              true, true, false,        # Linear velocity (x, y, z)
              false, false, true,       # Angular velocity (roll, pitch, yaw)
              false, false, false]      # Acceleration (x, y, z)
odom0_relative: false

# IMU input
imu0: imu
imu0_config: [false, false, false,      # Position (x, y, z)
              false, false, true,       # Orientation (roll, pitch, yaw)
              false, false, false,      # Linear velocity (x, y, z)
              false, false, false,      # Angular velocity (roll, pitch, yaw)
              false, false, false]      # Acceleration (x, y, z)
imu0_relative: true

# Pose input (ground truth)
pose0: pose_gt
pose0_config: [true, true, false,       # Position (x, y)
              false, false, true,       # Orientation (yaw)
              false, false, false,      # Linear velocity (x, y)
              false, false, false,      # Angular velocity (yaw)
              false, false, false]      # Acceleration
pose0_relative: false

# Odometry Measurement Noise Covariance (R)
odom0_covariance: [
  0.25, 0,    0,    0,    0,    0,      # x
  0,    0.25, 0,    0,    0,    0,      # y
  0,    0,    1e6, 0,    0,    0,       # z
  0,    0,    0,    1e6, 0,    0,       # roll
  0,    0,    0,    0,    1e6, 0,       # pitch
  0,    0,    0,    0,    0,    0.25   # yaw
]

# IMU Measurement Noise Covariance (R)
imu0_covariance: [
  1e6, 0,    0,    0,    0,    0,       # x
  0,    1e6, 0,    0,    0,    0,       # y
  0,    0,    1e6, 0,    0,    0,       # z
  0,    0,    0,    1e6, 0,    0,       # roll
  0,    0,    0,    0,    1e6, 0,       # pitch
  0,    0,    0,    0,    0,    0.25   # yaw 
]

# # Pose Measurement Noise Covariance (R) for Ground Truth
pose0_covariance: [
  0.001, 0,      0,    0,    0,    0,        # x
  0,      0.001, 0,    0,    0,    0,        # y
  0,      0,      1e6,  0,    0,    0,        # z
  0,      0,      0,    1e6,  0,    0,        # roll
  0,      0,      0,    0,    1e6,  0,        # pitch
  0,      0,      0,    0,    0,    0.001    # yaw
]