frequency: 30.0
sensor_timeout: 0.034
two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map

# Odometry input
odom0: odom
odom0_config: [false, false, false,   # Position (x, y, z)
              false, false, false,    # Orientation (roll, pitch, yaw)
              true, true, false,      # Linear velocity (x, y, z)
              false, false, true,     # Angular velocity (roll, pitch, yaw)
              false, false, false]    # Acceleration (x, y, z)
odom0_relative: false

# IMU input
imu0: imu
imu0_config: [false, false, false,    # Position (x, y, z)
              false, false, true,     # Orientation (roll, pitch, yaw)
              false, false, false,    # Linear velocity (x, y, z)
              false, false, false,    # Angular velocity (roll, pitch, yaw)
              false, false, false]    # Acceleration (x, y, z)
imu0_relative: true

# Pose input (ground truth)
pose0: pose_gt
pose0_config: [true, true, false,     # Position (x, y)
              false, false, true,     # Orientation (yaw)
              true, true, false,      # Linear velocity (x, y)
              false, false, true,     # Angular velocity (yaw)
              false, false, false]    # Acceleration
pose0_relative: false

# initial_state: [-1.9880502143006074, -0.4673281598919172, 0.0,
#                 0.0, 0.0, 0.0,
#                 0.0, 0.0, 0.0,
#                 0.0, 0.0, 0.0,
#                 0.0, 0.0, 0.0]