frequency: 30.0
sensor_timeout: 0.1
two_d_mode: true
publish_tf: false
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map

# Odometry input
odom0: odom
odom0_config: [false, false, false,   # Position (x, y, z)
              false, false, false,    # Orientation (roll, pitch, yaw)
              true, true, false,      # Linear velocity (x, y, z)
              false, false, true,     # Angular velocity (roll, pitch, yaw)
              false, false, false]    # Acceleration (x, y, z)
odom0_relative: false

# IMU input
# imu0: imu
# imu0_config: [false, false, false,    # Position (x, y, z)
#               false, false, false,     # Orientation (roll, pitch, yaw)
#               false, false, false,    # Linear velocity (x, y, z)
#               false, false, true,    # Angular velocity (roll, pitch, yaw)
#               false, false, false]    # Acceleration (x, y, z)
# imu0_relative: false

initial_state: [-2.302, 1.300, 0.0,   # Position (x, y, z)
                0.0, 0.0, -3.054,     # Orientation (roll, pitch, yaw)
                0.0, 0.0, 0.0,        # Linear velocity (x, y, z)
                0.0, 0.0, 0.0,        # Angular velocity (roll, pitch, yaw)
                0.0, 0.0, 0.0]        # Acceleration (x, y, z)